name: Deploy to GitHub Pages
on:
  push:
    branches: [master]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.2
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x
          dotnet-version: 7.0.100-rc.2.22477.23
          # Optional quality of the build. The possible values are: daily, signed, validated, preview, ga.
          dotnet-quality: preview
      - name: Publish .Net Core Project
        run: dotnet publish Stuffy.Website/Server/Stuffy.Website.Server.csproj -c Release -o release --nologo
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
